// 権限ルールのテスト。実行: npm i @firebase/rules-unit-testing firebase && firebase emulators:exec --only firestore --project demo-spachoco "node firebase/rules.test.mjs"
import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { doc, getDoc, setDoc, updateDoc, getDocs, collection, query, where, deleteDoc } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId: 'demo-spachoco', firestore: { rules: readFileSync(new URL('./firestore.rules', import.meta.url), 'utf8'), host: '127.0.0.1', port: 8080 } });
await env.withSecurityRulesDisabled(async (c) => {
  const d = c.firestore();
  const acc = (m, role, orgIds) => setDoc(doc(d, 'accounts', m), { memberId: m, role, orgIds });
  await acc('area@x.com', 'area', []);
  await acc('nmgr@x.com', 'manager', ['nika']);
  await acc('nexec@x.com', 'exec', ['nika']);
  await acc('staff@x.com', 'staff', ['nika', 'naikin']);
  await acc('fmgr@x.com', 'manager', ['fairy']);
  const M = (id, o) => setDoc(doc(d, 'meetings', id), { orgId: 'nika', status: 'published', visibility: 'exec', tasks: [{ id: 't', done: false }], title: 'x', ...o });
  await M('pubExec', {}); await M('pubOrg', { visibility: 'org' }); await M('draft', { status: 'draft', visibility: 'org' });
  await M('fairy', { orgId: 'fairy', visibility: 'org' });
  await setDoc(doc(d, 'orgs', 'nika'), { name: 'nika' });
});
const db = (email, verified = true) => env.authenticatedContext(email, { email, email_verified: verified }).firestore();
const R = [];
const t = async (name, p, ok) => { try { await (ok ? assertSucceeds(p) : assertFails(p)); R.push('PASS ' + name); } catch (e) { R.push('FAIL ' + name + ' ' + e.message.slice(0, 120)); } };
const root = db('spicechocolategroup@gmail.com');
await t('root reads all meetings', getDocs(collection(root, 'meetings')), true);
await t('root writes org', setDoc(doc(root, 'orgs', 'new'), { name: 'n' }), true);
await t('root writes account', setDoc(doc(root, 'accounts', 'new@x.com'), { role: 'staff', orgIds: [] }), true);
await t('unverified root denied', getDocs(collection(db('spicechocolategroup@gmail.com', false), 'meetings')), false);
await t('anon denied', getDoc(doc(env.unauthenticatedContext().firestore(), 'meetings', 'pubOrg')), false);
await t('unregistered denied', getDoc(doc(db('who@x.com'), 'meetings', 'pubOrg')), false);
await t('unregistered reads own account(missing) ok', getDoc(doc(db('who@x.com'), 'accounts', 'who@x.com')), true);
await t('area reads all', getDocs(collection(db('area@x.com'), 'meetings')), true);
await t('area edits fairy', updateDoc(doc(db('area@x.com'), 'meetings', 'fairy'), { title: 'y' }), true);
await t('area cannot write accounts', setDoc(doc(db('area@x.com'), 'accounts', 'z@x.com'), { role: 'owner' }), false);
const nm = db('nmgr@x.com');
await t('mgr query own org', getDocs(query(collection(nm, 'meetings'), where('orgId', 'in', ['nika']))), true);
await t('mgr full collection denied', getDocs(collection(nm, 'meetings')), false);
await t('mgr reads draft', getDoc(doc(nm, 'meetings', 'draft')), true);
await t('mgr cannot read fairy', getDoc(doc(nm, 'meetings', 'fairy')), false);
await t('mgr creates nika', setDoc(doc(nm, 'meetings', 'n1'), { orgId: 'nika', status: 'draft', visibility: 'org' }), true);
await t('mgr cannot create fairy', setDoc(doc(nm, 'meetings', 'n2'), { orgId: 'fairy', status: 'draft' }), false);
await t('mgr cannot move meeting to fairy', updateDoc(doc(nm, 'meetings', 'pubOrg'), { orgId: 'fairy' }), false);
await t('mgr cannot edit roster', setDoc(doc(nm, 'members', 'q'), { name: 'q' }), false);
await t('mgr cannot self-promote', setDoc(doc(nm, 'accounts', 'nmgr@x.com'), { role: 'owner', orgIds: [] }), false);
const ne = db('nexec@x.com');
await t('exec query published', getDocs(query(collection(ne, 'meetings'), where('orgId', 'in', ['nika']), where('status', '==', 'published'))), true);
await t('exec query w/o status denied', getDocs(query(collection(ne, 'meetings'), where('orgId', 'in', ['nika']))), false);
await t('exec reads exec-only', getDoc(doc(ne, 'meetings', 'pubExec')), true);
await t('exec cannot read draft', getDoc(doc(ne, 'meetings', 'draft')), false);
await t('exec checks task', updateDoc(doc(ne, 'meetings', 'pubExec'), { tasks: [{ id: 't', done: true }], updatedAt: 'now' }), true);
await t('exec cannot edit decisions', updateDoc(doc(ne, 'meetings', 'pubExec'), { decisions: ['x'] }), false);
await t('exec cannot create', setDoc(doc(ne, 'meetings', 'e1'), { orgId: 'nika', status: 'draft' }), false);
await t('exec cannot delete', deleteDoc(doc(ne, 'meetings', 'pubOrg')), false);
const st = db('staff@x.com');
await t('staff query org-visible', getDocs(query(collection(st, 'meetings'), where('orgId', 'in', ['nika', 'naikin']), where('status', '==', 'published'), where('visibility', '==', 'org'))), true);
await t('staff cannot read exec-only', getDoc(doc(st, 'meetings', 'pubExec')), false);
await t('staff reads org-visible', getDoc(doc(st, 'meetings', 'pubOrg')), true);
await t('staff cannot check task on exec-only', updateDoc(doc(st, 'meetings', 'pubExec'), { tasks: [] }), false);
await t('staff reads orgs', getDocs(collection(st, 'orgs')), true);
await t('staff cannot read others account', getDoc(doc(st, 'accounts', 'nmgr@x.com')), false);
await t('staff reads own account', getDoc(doc(st, 'accounts', 'staff@x.com')), true);
console.log(R.join('\n')); console.log(R.filter((x) => x.startsWith('FAIL')).length + ' failures');
await env.cleanup();
